module.exports = {
  apps: [
    {
      name: "judol-hunter-core",
      script: "src/index.js",
      instances: 1,
      exec_mode: "fork",
      watch: false,
      max_memory_restart: "1G",
      env: {
        NODE_ENV: "production",
        PORT: 50000,
      },
      error_file: "logs/pm2-core-error.log",
      out_file: "logs/pm2-core-out.log",
      log_file: "logs/pm2-core-combined.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      merge_logs: true,
      time: true,
    },
    {
      name: "ai-verificator",
      script: "src/ai-verificator/main.py",
      interpreter: "python3",
      instances: 1,
      exec_mode: "fork",
      watch: false,
      max_memory_restart: "2G",
      error_file: "logs/pm2-ai-error.log",
      out_file: "logs/pm2-ai-out.log",
      log_file: "logs/pm2-ai-combined.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      time: true,
    },
    {
      name: "dashboard",
      script: "src/dashboard/server.js",
      instances: 1,
      exec_mode: "fork",
      watch: false,
      max_memory_restart: "512M",
      env: {
        NODE_ENV: "production",
        PORT: 50001,
      },
      error_file: "logs/pm2-dashboard-error.log",
      out_file: "logs/pm2-dashboard-out.log",
      time: true,
    },
  ],
};
